//random-map.cpp
//Sarah Carter
//11-9-19
//This program requests a starting and ending number, then generates
//a map of uniformly distributed pseudo-random numbers, a map of
//normally distributed pr numbers, and a map of numbers generated by
//the rand() function. It prints histograms produced by the numbers
//in each of these maps.
                                          
#include <stdlib.h>
#include <iostream>
#include <iomanip>
#include <string>
#include <map>
#include <random>
#include <cmath>
#include <vector>
 
using std::random_device;
using std::mt19937;
using std::uniform_int_distribution;
using std::normal_distribution;

//calculate the mean of the first and last number entered by the user
int CalculateMean(int first, int last){
    //create a vector containing each number from first to last
    std::vector<int> nums;
    for(int c = first; c <= last; c++){
        nums.push_back(c);
    }
    //Add all the numbers up, then divide by how many there are.
    int ave = 0;
    for(auto i: nums){
        ave += i;
    }
    ave /= nums.size();
    
    return ave;
}

//Generate uniformly distributed pseudo-random numbers
int RandomBetweenU(int first, int last){
    random_device ru;
    mt19937 genu(ru());
    uniform_int_distribution<int> disu(first,last);
    return disu(genu);
}

//Generate normally distributed pseudo-random numbers
int RandomBetweenN(int first, int last){
    random_device rn;
    mt19937 genn(rn());
    normal_distribution<> disn(CalculateMean(first, last), 2);
    return disn(genn);
}

//Generate numbers with the rand() function, using the modulus
//calculation to restrict the range produced.
int RandomBetween(int first, int last){
    return rand() %(last - first + 1) + first;
}

//Print the histogram of the numbers contained in each map
void PrintDistribution(const std::map<int,int> &numbers){
    for (auto p : numbers) {
        std::cout << std::fixed << std::setprecision(1) << std::setw(2)
                  << p.first << ' ' << std::string(p.second/200, '*') << '\n';
    }
    std::cout << std::endl;
}

int main(){
    int first;
    int last;
    
    //Get range input from the user
    std::cout << "Enter a starting and an ending number: \n";
    std::cin >> first >> last;
    
    //Create each map containing the different pr numberes
    std::map<int, int> hist;
    std::map<int, int> histu;
    std::map<int, int> histn;
    for (int n = 0; n < 10000; ++n) {
        ++histn[std::round(RandomBetweenN(first, last))];
        ++histu[std::round(RandomBetweenU(first, last))];
        ++hist[std::round(RandomBetween(first, last))];
    }
    
    //Call the PrintDistribution function for each histogram map
    std::cout << "Uniform Distribution" << ":\n";
    PrintDistribution(histu);
    std::cout << "Normal Distribution" << ":\n";
    PrintDistribution(histn);
    std::cout << "Rand()" << ":\n";
    PrintDistribution(hist);

}
